package com.centerspotsolutions.blackscreenclock.lockscreenclockdisplay.superamoled.smartnightclock.utils;

import android.content.Context;
import android.content.SharedPreferences;
import android.util.Log;

import androidx.appcompat.app.AppCompatActivity;
import androidx.core.internal.view.SupportMenu;
import androidx.core.view.InputDeviceCompat;

import com.arbelkilani.clock.Clock;
import com.arbelkilani.clock.enumeration.ClockType;
import com.arbelkilani.clock.enumeration.analogical.ValueDisposition;
import com.arbelkilani.clock.enumeration.analogical.ValueStep;
import com.arbelkilani.clock.enumeration.analogical.ValueType;
import com.arbelkilani.clock.enumeration.numeric.NumericFormat;
import com.centerspotsolutions.blackscreenclock.lockscreenclockdisplay.superamoled.smartnightclock.R;


public class ConfigActivity extends AppCompatActivity {
    private static final String TAG = "ClockConfig";

    public Clock getConfig(Clock clock, Context context) {
        return configureClock(clock, context, context.getSharedPreferences("Settings", 0).getInt(Variables.CLOCK_NUMBER, 1));
    }

    public Clock configureClock(Clock clock, Context context, int i) {
        SharedPreferences sharedPreferences = context.getSharedPreferences("Settings", 0);
//        clock.setShow_date(sharedPreferences.getBoolean(Global.SHOW_DATE, true));
        switch (i) {
            case 601:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_601);
                break;
            case 602:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color5);
                clock.setHoursNeedleColor(R.color.color5);
                clock.setMinutesNeedleColor(R.color.color5);
                clock.setCenterInnerColor(R.color.color5);
                clock.setCenterOuterColor(R.color.color5);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_602);
                break;
            case 603:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color2);
                clock.setHoursNeedleColor(R.color.color2);
                clock.setMinutesNeedleColor(R.color.color2);
                clock.setCenterInnerColor(R.color.color2);
                clock.setCenterOuterColor(R.color.color2);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_603);
                break;
            case 604:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_604);
                break;
            case 605:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_605);
                break;
            case 606:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_606);
                break;
            case 607:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_607);
                break;
            case 608:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_608);
                break;
            case 609:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_609);
                break;
            case 610:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_610);
                break;
            case 611:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.black);
                clock.setHoursNeedleColor(R.color.black);
                clock.setMinutesNeedleColor(R.color.black);
                clock.setCenterInnerColor(R.color.black);
                clock.setCenterOuterColor(R.color.black);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_611);
                break;
            case 612:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_612);
                break;
            case 613:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_613);
                break;
            case 614:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_614);
                break;
            case 615:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_615);
                break;
            case 616:
                Log.d(TAG, "getConfigAll: called 616");
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_616);
                break;
            case 617:
                Log.d(TAG, "getConfigAll: called 617");
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_617);
                break;
            case 618:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_618);
                break;
            case 619:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_619);
                break;
            case 620:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_620);
                break;
            case 621:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_621);
                break;
            case 622:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_622);
                break;
            case 623:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_623);
                break;
            case 624:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_624);
                break;
            case 625:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_625);
                break;
            case 626:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_626);
                break;
            case 627:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_627);
                break;
            case 628:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_628);
                break;
            case 629:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_629);
                break;
            case 630:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_630);
                break;
            case 631:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_631);
                break;
            case 632:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_632);
                break;
            case 633:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_633);
                break;
            case 634:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_634);
                break;
            case 635:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_635);
                break;
            case 636:

                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.white);
                clock.setHoursNeedleColor(R.color.white);
                clock.setMinutesNeedleColor(R.color.white);
                clock.setCenterInnerColor(R.color.white);
                clock.setCenterOuterColor(R.color.white);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.dial_636);
                break;
            case 1:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color1);
                clock.setHoursNeedleColor(R.color.color1);
                clock.setMinutesNeedleColor(R.color.color1);
                clock.setCenterInnerColor(R.color.color1);
                clock.setCenterOuterColor(R.color.color1);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial1);
                break;
            case 2:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color2);
                clock.setHoursNeedleColor(R.color.color2);
                clock.setMinutesNeedleColor(R.color.color2);
                clock.setCenterInnerColor(R.color.color2);
                clock.setCenterOuterColor(R.color.color2);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial2);
                break;
            case 3:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color3);
                clock.setHoursNeedleColor(R.color.color3);
                clock.setMinutesNeedleColor(R.color.color3);
                clock.setCenterInnerColor(R.color.color3);
                clock.setCenterOuterColor(R.color.color3);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial3);
                break;
            case 4:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color4);
                clock.setHoursNeedleColor(R.color.color4);
                clock.setMinutesNeedleColor(R.color.color4);
                clock.setCenterInnerColor(R.color.color4);
                clock.setCenterOuterColor(R.color.color4);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial4);
                break;
            case 5:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color5);
                clock.setHoursNeedleColor(R.color.color5);
                clock.setMinutesNeedleColor(R.color.color5);
                clock.setCenterInnerColor(R.color.color5);
                clock.setCenterOuterColor(R.color.color5);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial5);
                break;
            case 6:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color6);
                clock.setHoursNeedleColor(R.color.color6);
                clock.setMinutesNeedleColor(R.color.color6);
                clock.setCenterInnerColor(R.color.color6);
                clock.setCenterOuterColor(R.color.color6);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial6);
                break;
            case 7:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.color7);
                clock.setHoursNeedleColor(R.color.color7);
                clock.setMinutesNeedleColor(R.color.color7);
                clock.setCenterInnerColor(R.color.color7);
                clock.setCenterOuterColor(R.color.color7);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial7);
                break;
            case 8:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial8);
                break;
            case 9:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial9);
                break;
            case 10:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial10);
                break;
            case 11:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial11);
                break;
            case 12:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial12);
                break;
            case 13:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial13);
                break;
            case 14:
                clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                clock.setSecondsNeedleColor(R.color.colorWhite);
                clock.setHoursNeedleColor(R.color.colorWhite);
                clock.setMinutesNeedleColor(R.color.colorWhite);
                clock.setCenterInnerColor(R.color.colorWhite);
                clock.setCenterOuterColor(R.color.colorWhite);
                clock.setShowBorder(false);
                clock.setShowDegrees(false);
                clock.setClockType(ClockType.analogical);
                clock.showCenter(true);
                clock.setShowHoursValues(true);
                clock.setValueType(ValueType.none);
                clock.setValueStep(ValueStep.full);
                clock.setValueDisposition(ValueDisposition.regular);
                clock.setShowMinutesValues(false);
                clock.setClockBackground(R.drawable.bg_dial14);
                break;
            case 15:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(true);
                clock.setBorderColor(-65281);
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(-65281);
                break;
            case 16:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(-1);
                break;
            case 17:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_thin);
                clock.setValuesColor(SupportMenu.CATEGORY_MASK);
//                clock.setClockNumber(1);
                break;
            case 18:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(-16776961);
//                clock.setClockNumber(1);
                break;
            case 19:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.regular4);
                clock.setValuesColor(-16711936);
//                clock.setClockNumber(1);
                break;
            case 20:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.grishenko_nbp);
                clock.setValuesColor(InputDeviceCompat.SOURCE_ANY);
//                clock.setClockNumber(1);
                break;
            case 21:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesColor(-1);
                clock.setValuesFont(R.font.regular4);
//                clock.setClockNumber(1);
                break;
            case 22:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(-16711681);
//                clock.setClockNumber(1);
                break;
            case 23:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(SupportMenu.CATEGORY_MASK);
//                clock.setClockNumber(1);
                break;
            case 24:
//                clock.setClockType(ClockType.cus_digital);
                clock.setShowBorder(false);
                clock.setBorderColor(sharedPreferences.getInt(Variables.VALUES_COLOR, -1));
                clock.setNumericFormat(NumericFormat.hour_12);
                clock.setValuesFont(R.font.proxima_nova_regular);
                clock.setValuesColor(-7829368);
//                clock.setClockNumber(1);
                break;
            default:
                Log.d(TAG, "getConfigAll: default called");
                switch (i) {
                    case 43:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial15);
                        break;
                    case 44:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial16);
                        break;
                    case 45:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial17);
                        break;
                    case 46:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial18);
                        break;
                    case 47:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial19);
                        break;
                    case 48:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial20);
                        break;
                    case 49:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial21);
                        break;
                    case 50:
                        clock.setShowSecondsNeedle(sharedPreferences.getBoolean(Variables.SHOW_SECONDS_NEEDLE, true));
                        clock.setSecondsNeedleColor(R.color.colorWhite);
                        clock.setHoursNeedleColor(R.color.colorWhite);
                        clock.setMinutesNeedleColor(R.color.colorWhite);
                        clock.setCenterInnerColor(R.color.colorWhite);
                        clock.setCenterOuterColor(R.color.colorWhite);
                        clock.setShowBorder(false);
                        clock.setShowDegrees(false);
                        clock.setClockType(ClockType.analogical);
                        clock.showCenter(true);
                        clock.setShowHoursValues(true);
                        clock.setValueType(ValueType.none);
                        clock.setValueStep(ValueStep.full);
                        clock.setValueDisposition(ValueDisposition.regular);
                        clock.setShowMinutesValues(false);
                        clock.setClockBackground(R.drawable.bg_dial22);
                        break;
                }
        }
        return clock;
    }
}
